### ISSUE TITLE
Need to reset credentials

### ISSUE THREAD

**Issue by jasonbarbee** [OrkoHunter/keep#16]
I didn't do keep init first, so the folder wasn't there, and keep credential file failed to create.
Register fails because the user exists on your heroku api server.
How can I reset the credentials?

**Comment by OrkoHunter** [comment]
Can you please send me an email from the email you registered ? I will reset the user. However, you can register with any username and that does not need to be your email id.

**Comment by jasonbarbee** [comment]
jason.barbee@gmail.com

**Comment by OrkoHunter** [comment]
Done ! Please try `keep init` again.

**Comment by jasonbarbee** [comment]
Thanks that did work for me.
