### ISSUE TITLE
Why not just a dotfiles repo and grep/ag?

### ISSUE THREAD

**Issue by zamber** [OrkoHunter/keep#18]
I have solved this problem by keeping a unified dotfiles repo that pulls in additional `*.zsh` files depending on the hostname. Installation is basic:

```
{package manager of choice} install zsh git
git clone {my dotfiles repo} ~/.dotfiles/
cd ~/.dotfiles && ./install
```

[Dotbot](https://github.com/anishathalye/dotbot) takes care of installing additional stuff and linking the `.zsh` files (among other shared conf). Setting it up on a new machine is a breeze and updating the repo boils down to a `git pull` and `. ~/.zshrc` (which can be aliased).

If you want to have a way to lookup stuff then just set an alias for grepping/ag the `~/.dotfiles/` folder and keep comments on each alias. Running stuff is just typing in the alias (which is auto-completed y zsh either ways).

This has an additional bonus of a shared repository of aliases (which by design are mnemonic and easy to remember). Also Cross-distribution stuff can be abstracted away too with basic conditional logic so that `i {package name}` will install stuff no matter what distro I'm currently on, etc.

Also the hostname-based includes allow me to exclude stuff that are not required (eg. ADB stuff on my Raspberry Pi which I use only through SSH or setting a lightweight prompt for it).

On top of that there are no external dependencies (not counting ZSH, git and python 2.6=>).

What advantage this project has over that setup?

**Comment by OrkoHunter** [comment]
> What advantage this project has over that setup?

One possible answer to it is that setting up this project takes very less (zero?) effort. Maintaining dotfiles is a obviously a good thing, but is not required and not preferred by every single Unix user.
