### ISSUE TITLE
Hangs indefinitely.

### ISSUE THREAD

**Issue by TwistingTwists** [OrkoHunter/keep#2]
`keep watch -n 1 free -h` hangs indefinitely. Installed using `pip install keep`. Any solutions?

**Comment by OrkoHunter** [comment]
After
```
keep watch -n 1 free -h
```
`keep` asks you for one line description about the command you are trying to store. I think that's not hang.

But it looks so. Thanks for reporting. It should be more explicit.

**Comment by OrkoHunter** [comment]
@TwistingTwists Comments?

**Comment by TwistingTwists** [comment]
Ah! Okay. May be a prompt would help? It works. :) 
Or, something similar to `git commit -m "keep me forever" `?

**Comment by OrkoHunter** [comment]
A prompt is going to be added. :)
