### ISSUE TITLE
keep rm - How does it work?

### ISSUE THREAD

**Issue by msti** [OrkoHunter/keep#20]
Hi,
Thanks for this great util! 

How can I remove a command? I tried removing by description and the command but it did not work.

**Comment by OrkoHunter** [comment]
`keep rm` removes the command you enter to its prompt. You can also manually remove the entri in your `~/.keep/commands.json` file.

I wish I could implement the feature to remove by description.

**Comment by msti** [comment]
It looks like a bug then?

<img width="325" alt="shot_20170703-104229" src="https://cloud.githubusercontent.com/assets/808110/23648323/e0ec8486-0322-11e7-9c2a-ab93db8e9ae4.png">

**Comment by msti** [comment]
forget it.. there was an extra space at the end of the command.

**Comment by OrkoHunter** [comment]
Ah! This had happened with me too. Will implement this feature too.

**Comment by msti** [comment]
Maybe add a numbered list and refer to the id instead of the command or description ?

**Comment by OrkoHunter** [comment]
That would do as well!
