### ISSUE TITLE
`keep init` not being run makes `keep register` fail in a non-recoverable way

### ISSUE THREAD

**Issue by EdJoJob** [OrkoHunter/keep#22]
I tried registering without doing `keep init` and just tried doing `keep register`, when I did this the registration happened on the server side, and the key was received, but without the directory being set up, I was unable to recover the key generated along with my primary email.

**Comment by OrkoHunter** [comment]
Thanks for the issue @EdJoJob. `keep register` must verify the initialization before it proceeds.

Meanwhile you can clean up with this.
```
rm -rf ~/.keep
keep init
```

If it says, user already exists, please drop an email to me (`himanshumishra@iitkgp.ac.in`) with that id, I'll reset your credentials.

**Comment by EdJoJob** [comment]
I do have a code fix in mind for this, and a pull request will follow as soon as I have the time to be at a non-work computer

**Comment by OrkoHunter** [comment]
@EdJoJob That is great ! Looking forward.
