### ISSUE TITLE
Command templates?

### ISSUE THREAD

**Issue by TwistingTwists** [OrkoHunter/keep#26]
How about command templates? 
say I have to run following command again n again. 
`` python logplot.py run_NPT_long_prod_jan_30.txt Step TotEng``

Is there a way I can replace the `.txt` file each time? A command template or something similar is what I can think of now.

**Comment by OrkoHunter** [comment]
Hey

Yes, you can save a command with a parameters. See https://github.com/OrkoHunter/keep/pull/24
```
python logplot.py $filename Step TotEng
```

**Comment by TwistingTwists** [comment]
That's lovely! Thanks a lot!
