### ISSUE TITLE
Store data in gist

### ISSUE THREAD

**Issue by Nklya** [OrkoHunter/keep#31]
Hello.

I have an enhancement proposal.

I think it will be great add option to save settings in personal github gist.

For example, many extentions in Atom and VS code sync settings by this way:
https://github.com/atom-community/sync-settings
https://github.com/shanalikhan/code-settings-sync

**Comment by OrkoHunter** [comment]
Hello @Nklya !

Thanks for the suggestion. I would like to ask for some more clarification though. There are basically two "settings" file of the user, their credentials and their stored commands. Which one(s) would you prefer to store on the gist?

**Comment by Nklya** [comment]
I mean stored commands.

This will be useful for people, who want to sync between computers and control where to store settings in the cloud.

**Comment by OrkoHunter** [comment]
+1
Will move to github gist soon. Currently the sync *is* available but from a private server.
