### ISSUE TITLE
 How to use `keep` without the sync?

### ISSUE THREAD

**Issue by halloleo** [OrkoHunter/keep#45]
Because of Issue #41, I'd like to use `keep` without the sync. What's the best way to do this?

**Comment by OrkoHunter** [comment]
Thank you for reporting @halloleo !

Please update keep to use.
```
pip3 --no-cache-dir install -U keep==2.5.2
```

**Comment by halloleo** [comment]
Thanks @OrkoHunter. Works now well.  

PS: Syncing I do via Dropbox and a symlink to `~/.keep`. :-)

**Comment by OrkoHunter** [comment]
Awesome! :)
