### ISSUE TITLE
keep is slow (or maybe click is)

### ISSUE THREAD

**Issue by OrkoHunter** [OrkoHunter/keep#48]
keep --help takes about 0.42 seconds. The python functions inside utils all take time in milliseconds.

I have absolutely no clue. Maybe `click` is adding a lot of overhead.

**Comment by OrkoHunter** [comment]
I will try to use `argparse` and see what are the results.

**Comment by OrkoHunter** [comment]
I've always wanted to use https://github.com/google/python-fire

**Comment by rahuliyer95** [comment]
I believe the latest version of click should have resolved this and can be closed
