### ISSUE TITLE
please add an option to just print out the command

### ISSUE THREAD

**Issue by justrajdeep** [OrkoHunter/keep#51]
Hi 

Please add an option just to print out the bare command, not run them.

Thanks

**Comment by OrkoHunter** [comment]
Hi @justrajdeep !

Can you please let me know the expected behaviour? Do `keep list` and `keep grep` not help?

**Comment by justrajdeep** [comment]
Hi 

sorry for the late reply

`keep list` shows the commands in a tabular form, `keep grep` list them with the description. I am looking for just the raw command so that i can just pipe it to `sh` and run it, or maybe redirect it to a file.
