### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by dna75** [OrkoHunter/keep#54]
I installed Keep on a new server.
When I use Python 3.6 I get an error;
Traceback (most recent call last):
  File "/usr/bin/keep", line 6, in <module>
    from keep.cli import cli
ModuleNotFoundError: No module named 'keep'
[root@srv4 ~]# keep pull
Traceback (most recent call last):
  File "/usr/bin/keep", line 6, in <module>
    from keep.cli import cli
ModuleNotFoundError: No module named 'keep'

**Comment by rahuliyer95** [comment]
How did you install keep?

**Comment by dna75** [comment]
I used 'pip3 install keep'

**Comment by rahuliyer95** [comment]
I'm sorry I'm not able to reproduce this issue. Can you please  share some more steps on replicating this issue

**Comment by dna75** [comment]
I installed Python 3.7 en now it works perfectly. Very strange because my. other server has the same config and is using Python 3.6.3 without any problems.
