### ISSUE TITLE
[Feature] autocomplete run

### ISSUE THREAD

**Issue by lukruh** [OrkoHunter/keep#60]
Nice and simple tool! Just installed it today. 
My first idea to improve it slightly: suggestions after the run command when pressing tab.
I don't know about the bash stuff, but if it's easy to implement, it would be worth. At least I would probably use it a lot ;)

**Comment by OrkoHunter** [comment]
Thanks for the suggestion @lukruh. I'll keep the issue open. :)

**Comment by ahadafzal** [comment]
@lukruh good suggestions , I too will look forward to it.
