### ISSUE TITLE
make a new release

### ISSUE THREAD

**Issue by ahadafzal** [OrkoHunter/keep#62]
some of the issues are fixed, but i am still getting error when I install keep using pip.
for eg. 
![Screenshot from 2020-02-19 21-22-48](https://user-images.githubusercontent.com/33332089/74848966-33d74a80-535e-11ea-9613-8600f68a69af.png)
This error is already fixed and merged in master.

**Comment by OrkoHunter** [comment]
Thank you! Just released 2.9
