### ISSUE TITLE
Can't pull if there is no commands

### ISSUE THREAD

**Issue by rluvaton** [OrkoHunter/keep#64]
Can't pull when there are no commands

> Error trace:
> ```
> home-server@home-server:~$ keep pull
> [CRITICAL] Replace local commands with GitHub gist
> Gist URL : https://gist.github.com/<my-gist-id>? [y/N]: y
> Traceback (most recent call last):
>   File "/usr/local/bin/keep", line 10, in <module>
>     sys.exit(cli())
>   File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/click/decorators.py", line 64, in new_func
>     return ctx.invoke(f, obj, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/keep/commands/cmd_pull.py", line 23, in cli
>     os.remove(commands_file_path)
> FileNotFoundError: [Errno 2] No such file or directory: '/home/home-server/.keep/commands.json'
> ```

**Comment by OrkoHunter** [comment]
Thanks for reporting! This behavior can be fixed. Feel free to create a Pull Request :)

**Comment by rluvaton** [comment]
@OrkoHunter Fixed here #65 (I didn’t test)
