### ISSUE TITLE
Keep edit won't save an empty file

### ISSUE THREAD

**Issue by chrisngyn** [OrkoHunter/keep#66]
When I `keep edit` and try to delete all my commands then try to save the file, it doesn't save my changes. Therefore when I type `keep list` again it shows my list with my old commands and without my changes. Not sure if this is a huge problem because you could just `keep rm` all your commands or just `keep init` to get an empty list again but thought I'd mention it.

**Comment by OrkoHunter** [comment]
Oh thanks for creating the issue! Yes, `keep init` solve this but I believe, it should be allowed to delete all commands manually using `keep edit` too.
