### ISSUE TITLE
How to activate venv in keep ?

### ISSUE THREAD

**Issue by rushic24** [OrkoHunter/keep#87]
I have a venv in /mnt/external
To activate that I usually do `source /mnt/external/venv/bin/activate`

Keep doesn't seem to work with this command.

**Comment by rahuliyer95** [comment]
Similar to #57  #75, keep commands run in a subshell that gets erased after the command is complete. This is the reason your `source` command cannot work with keep.

**Comment by rushic24** [comment]
@rahuliyer95 One workaround is to use $eval 

![image](https://user-images.githubusercontent.com/6279035/174934959-ad844e59-9e19-4c3a-847c-b7e34a2e8bab.png)
