### ISSUE TITLE
Arrow keys not working when creating a new command

### ISSUE THREAD

**Issue by Dennis-Rall** [OrkoHunter/keep#88]
Pressing the arrow keys in the 'Command' Promt, does not move your cursor. It just adds the values of the arrow keys. It would be nice to copy a command into the promt and be able to edit it.

![image](https://user-images.githubusercontent.com/56480601/174959945-390fe114-f8aa-4aef-9837-42b9278c2696.png)

**Comment by rahuliyer95** [comment]
Unfortunately, this is a limitation of the [click](https://click.palletsprojects.com/en/8.1.x/api/?highlight=prompt#click.prompt) library used to accept user input. I would recommend using [rlwrap](https://linux.die.net/man/1/rlwrap) to handle this. Example,
```sh
rlwrap keep new
```
