### ISSUE TITLE
Feature: keep new inline

### ISSUE THREAD

**Issue by ZachBien** [OrkoHunter/keep#93]
Creating a new keep requires me to enter the command after a prompt. But I would prefer to have a shortcut where I can do 

```shell
keep new my command to keep
``` 
And that will create a quick keep (without description or alias)

That will allow me to do something like 

```shell
$ my command that I can't remember
$ keep new !!
```
Simple!

**Comment by rahuliyer95** [comment]
You can try 

```sh
$ my command that I can't remember
$ keep new --cmd "!!" --desc "my command"
```
