### ISSUE TITLE
source command not working

### ISSUE THREAD

**Issue by Harsh-0-7** [OrkoHunter/keep#94]
not working source environ.txt 
![image](https://github.com/OrkoHunter/keep/assets/44116156/ea885183-5a88-4204-9a37-1c370b91e8b9)

It is working fine if we type command source environ.txt  and run. But when i save in keep and run. It gives error.

**Comment by rahuliyer95** [comment]
Similar to #57 #75 #867, keep commands run in a subshell that gets erased after the command is complete. This is the reason your source command cannot work with keep.

**Comment by Harsh-0-7** [comment]
I am just wondering, can't we add option to run command in shell and in subshell?

**Comment by rahuliyer95** [comment]
> @rahuliyer95 Thanks for the explanation. I am just wondering, can't we add option to run command in shell and in subshell?

From [#57](https://github.com/OrkoHunter/keep/issues/57#issuecomment-534630488)

> [This Q&A on stackoverflow](https://stackoverflow.com/questions/1506010/how-to-use-export-with-python-on-linux) says that it is not possible to use the export command as it is from Python. So, perhaps keep should give out a warning that export command will not work from Python or there may be a workaround to it.
